[32;01m * [39;49;00mPackage:    app-text/xml2rfc-3.3.0
[32;01m * [39;49;00mRepository: flow
[32;01m * [39;49;00mMaintainer: flo@geekplace.eu
[32;01m * [39;49;00mUSE:        abi_x86_64 amd64 elibc_glibc kernel_linux python_targets_python3_7 test userland_GNU
[32;01m * [39;49;00mFEATURES:   compressdebug network-sandbox preserve-libs sandbox splitdebug test userpriv usersandbox
[32;01m * [39;49;00mPackage:    app-text/xml2rfc-3.3.0
[32;01m * [39;49;00mRepository: flow
[32;01m * [39;49;00mMaintainer: flo@geekplace.eu
[32;01m * [39;49;00mUSE:        abi_x86_64 amd64 elibc_glibc kernel_linux python_targets_python3_7 test userland_GNU
[32;01m * [39;49;00mFEATURES:   compressdebug network-sandbox preserve-libs sandbox splitdebug test userpriv usersandbox
>>> Unpacking source...
>>> Unpacking xml2rfc-3.3.0.tar.gz to /data-scratch/var-tmp/portage/app-text/xml2rfc-3.3.0/work
>>> Source unpacked in /data-scratch/var-tmp/portage/app-text/xml2rfc-3.3.0/work
>>> Preparing source in /data-scratch/var-tmp/portage/app-text/xml2rfc-3.3.0/work/xml2rfc-3.3.0 ...
>>> Source prepared.
>>> Configuring source in /data-scratch/var-tmp/portage/app-text/xml2rfc-3.3.0/work/xml2rfc-3.3.0 ...
>>> Source configured.
>>> Compiling source in /data-scratch/var-tmp/portage/app-text/xml2rfc-3.3.0/work/xml2rfc-3.3.0 ...
 [32;01m*[0m python3_7: running distutils-r1_run_phase distutils-r1_python_compile
python3.7 setup.py build -j 18
running build
running build_py
creating /data-scratch/var-tmp/portage/app-text/xml2rfc-3.3.0/work/xml2rfc-3.3.0-python3_7/lib/xml2rfc
copying xml2rfc/__init__.py -> /data-scratch/var-tmp/portage/app-text/xml2rfc-3.3.0/work/xml2rfc-3.3.0-python3_7/lib/xml2rfc
copying xml2rfc/parser.py -> /data-scratch/var-tmp/portage/app-text/xml2rfc-3.3.0/work/xml2rfc-3.3.0-python3_7/lib/xml2rfc
copying xml2rfc/strings.py -> /data-scratch/var-tmp/portage/app-text/xml2rfc-3.3.0/work/xml2rfc-3.3.0-python3_7/lib/xml2rfc
copying xml2rfc/walkpdf.py -> /data-scratch/var-tmp/portage/app-text/xml2rfc-3.3.0/work/xml2rfc-3.3.0-python3_7/lib/xml2rfc
copying xml2rfc/boilerplate_rfc_7841.py -> /data-scratch/var-tmp/portage/app-text/xml2rfc-3.3.0/work/xml2rfc-3.3.0-python3_7/lib/xml2rfc
copying xml2rfc/boilerplate_id_guidelines.py -> /data-scratch/var-tmp/portage/app-text/xml2rfc-3.3.0/work/xml2rfc-3.3.0-python3_7/lib/xml2rfc
copying xml2rfc/scripts.py -> /data-scratch/var-tmp/portage/app-text/xml2rfc-3.3.0/work/xml2rfc-3.3.0-python3_7/lib/xml2rfc
copying xml2rfc/boilerplate_tlp.py -> /data-scratch/var-tmp/portage/app-text/xml2rfc-3.3.0/work/xml2rfc-3.3.0-python3_7/lib/xml2rfc
copying xml2rfc/debug.py -> /data-scratch/var-tmp/portage/app-text/xml2rfc-3.3.0/work/xml2rfc-3.3.0-python3_7/lib/xml2rfc
copying xml2rfc/run.py -> /data-scratch/var-tmp/portage/app-text/xml2rfc-3.3.0/work/xml2rfc-3.3.0-python3_7/lib/xml2rfc
copying xml2rfc/utils.py -> /data-scratch/var-tmp/portage/app-text/xml2rfc-3.3.0/work/xml2rfc-3.3.0-python3_7/lib/xml2rfc
copying xml2rfc/log.py -> /data-scratch/var-tmp/portage/app-text/xml2rfc-3.3.0/work/xml2rfc-3.3.0-python3_7/lib/xml2rfc
creating /data-scratch/var-tmp/portage/app-text/xml2rfc-3.3.0/work/xml2rfc-3.3.0-python3_7/lib/xml2rfc/writers
copying xml2rfc/writers/v2v3.py -> /data-scratch/var-tmp/portage/app-text/xml2rfc-3.3.0/work/xml2rfc-3.3.0-python3_7/lib/xml2rfc/writers
copying xml2rfc/writers/__init__.py -> /data-scratch/var-tmp/portage/app-text/xml2rfc-3.3.0/work/xml2rfc-3.3.0-python3_7/lib/xml2rfc/writers
copying xml2rfc/writers/doc.py -> /data-scratch/var-tmp/portage/app-text/xml2rfc-3.3.0/work/xml2rfc-3.3.0-python3_7/lib/xml2rfc/writers
copying xml2rfc/writers/text.py -> /data-scratch/var-tmp/portage/app-text/xml2rfc-3.3.0/work/xml2rfc-3.3.0-python3_7/lib/xml2rfc/writers
copying xml2rfc/writers/raw_txt.py -> /data-scratch/var-tmp/portage/app-text/xml2rfc-3.3.0/work/xml2rfc-3.3.0-python3_7/lib/xml2rfc/writers
copying xml2rfc/writers/pdf.py -> /data-scratch/var-tmp/portage/app-text/xml2rfc-3.3.0/work/xml2rfc-3.3.0-python3_7/lib/xml2rfc/writers
copying xml2rfc/writers/paginated_txt.py -> /data-scratch/var-tmp/portage/app-text/xml2rfc-3.3.0/work/xml2rfc-3.3.0-python3_7/lib/xml2rfc/writers
copying xml2rfc/writers/expand.py -> /data-scratch/var-tmp/portage/app-text/xml2rfc-3.3.0/work/xml2rfc-3.3.0-python3_7/lib/xml2rfc/writers
copying xml2rfc/writers/html.py -> /data-scratch/var-tmp/portage/app-text/xml2rfc-3.3.0/work/xml2rfc-3.3.0-python3_7/lib/xml2rfc/writers
copying xml2rfc/writers/nroff.py -> /data-scratch/var-tmp/portage/app-text/xml2rfc-3.3.0/work/xml2rfc-3.3.0-python3_7/lib/xml2rfc/writers
copying xml2rfc/writers/unprep.py -> /data-scratch/var-tmp/portage/app-text/xml2rfc-3.3.0/work/xml2rfc-3.3.0-python3_7/lib/xml2rfc/writers
copying xml2rfc/writers/preptool.py -> /data-scratch/var-tmp/portage/app-text/xml2rfc-3.3.0/work/xml2rfc-3.3.0-python3_7/lib/xml2rfc/writers
copying xml2rfc/writers/debug.py -> /data-scratch/var-tmp/portage/app-text/xml2rfc-3.3.0/work/xml2rfc-3.3.0-python3_7/lib/xml2rfc/writers
copying xml2rfc/writers/legacy_html.py -> /data-scratch/var-tmp/portage/app-text/xml2rfc-3.3.0/work/xml2rfc-3.3.0-python3_7/lib/xml2rfc/writers
copying xml2rfc/writers/base.py -> /data-scratch/var-tmp/portage/app-text/xml2rfc-3.3.0/work/xml2rfc-3.3.0-python3_7/lib/xml2rfc/writers
copying xml2rfc/writers/expanded_xml.py -> /data-scratch/var-tmp/portage/app-text/xml2rfc-3.3.0/work/xml2rfc-3.3.0-python3_7/lib/xml2rfc/writers
creating /data-scratch/var-tmp/portage/app-text/xml2rfc-3.3.0/work/xml2rfc-3.3.0-python3_7/lib/xml2rfc/util
copying xml2rfc/util/num.py -> /data-scratch/var-tmp/portage/app-text/xml2rfc-3.3.0/work/xml2rfc-3.3.0-python3_7/lib/xml2rfc/util
copying xml2rfc/util/__init__.py -> /data-scratch/var-tmp/portage/app-text/xml2rfc-3.3.0/work/xml2rfc-3.3.0-python3_7/lib/xml2rfc/util
copying xml2rfc/util/fonts.py -> /data-scratch/var-tmp/portage/app-text/xml2rfc-3.3.0/work/xml2rfc-3.3.0-python3_7/lib/xml2rfc/util
copying xml2rfc/util/name.py -> /data-scratch/var-tmp/portage/app-text/xml2rfc-3.3.0/work/xml2rfc-3.3.0-python3_7/lib/xml2rfc/util
copying xml2rfc/util/postal.py -> /data-scratch/var-tmp/portage/app-text/xml2rfc-3.3.0/work/xml2rfc-3.3.0-python3_7/lib/xml2rfc/util
copying xml2rfc/util/unicode.py -> /data-scratch/var-tmp/portage/app-text/xml2rfc-3.3.0/work/xml2rfc-3.3.0-python3_7/lib/xml2rfc/util
copying xml2rfc/util/date.py -> /data-scratch/var-tmp/portage/app-text/xml2rfc-3.3.0/work/xml2rfc-3.3.0-python3_7/lib/xml2rfc/util
creating /data-scratch/var-tmp/portage/app-text/xml2rfc-3.3.0/work/xml2rfc-3.3.0-python3_7/lib/xml2rfc/uniscripts
copying xml2rfc/uniscripts/__init__.py -> /data-scratch/var-tmp/portage/app-text/xml2rfc-3.3.0/work/xml2rfc-3.3.0-python3_7/lib/xml2rfc/uniscripts
copying xml2rfc/uniscripts/unidata.py -> /data-scratch/var-tmp/portage/app-text/xml2rfc-3.3.0/work/xml2rfc-3.3.0-python3_7/lib/xml2rfc/uniscripts
creating /data-scratch/var-tmp/portage/app-text/xml2rfc-3.3.0/work/xml2rfc-3.3.0-python3_7/lib/xml2rfc/templates
copying xml2rfc/templates/rfc2629.dtd -> /data-scratch/var-tmp/portage/app-text/xml2rfc-3.3.0/work/xml2rfc-3.3.0-python3_7/lib/xml2rfc/templates
copying xml2rfc/templates/base.html -> /data-scratch/var-tmp/portage/app-text/xml2rfc-3.3.0/work/xml2rfc-3.3.0-python3_7/lib/xml2rfc/templates
copying xml2rfc/templates/rfc2629-other.ent -> /data-scratch/var-tmp/portage/app-text/xml2rfc-3.3.0/work/xml2rfc-3.3.0-python3_7/lib/xml2rfc/templates
copying xml2rfc/templates/doc.yaml -> /data-scratch/var-tmp/portage/app-text/xml2rfc-3.3.0/work/xml2rfc-3.3.0-python3_7/lib/xml2rfc/templates
copying xml2rfc/templates/doc.xml -> /data-scratch/var-tmp/portage/app-text/xml2rfc-3.3.0/work/xml2rfc-3.3.0-python3_7/lib/xml2rfc/templates
copying xml2rfc/templates/address_card.html -> /data-scratch/var-tmp/portage/app-text/xml2rfc-3.3.0/work/xml2rfc-3.3.0-python3_7/lib/xml2rfc/templates
copying xml2rfc/templates/rfc2629-xhtml.ent -> /data-scratch/var-tmp/portage/app-text/xml2rfc-3.3.0/work/xml2rfc-3.3.0-python3_7/lib/xml2rfc/templates
creating /data-scratch/var-tmp/portage/app-text/xml2rfc-3.3.0/work/xml2rfc-3.3.0-python3_7/lib/xml2rfc/data
copying xml2rfc/data/mt.css -> /data-scratch/var-tmp/portage/app-text/xml2rfc-3.3.0/work/xml2rfc-3.3.0-python3_7/lib/xml2rfc/data
copying xml2rfc/data/v3.rnc -> /data-scratch/var-tmp/portage/app-text/xml2rfc-3.3.0/work/xml2rfc-3.3.0-python3_7/lib/xml2rfc/data
copying xml2rfc/data/Strict-Signature.rng -> /data-scratch/var-tmp/portage/app-text/xml2rfc-3.3.0/work/xml2rfc-3.3.0-python3_7/lib/xml2rfc/data
copying xml2rfc/data/xml2rfc-v3-emacs-nxml.rng -> /data-scratch/var-tmp/portage/app-text/xml2rfc-3.3.0/work/xml2rfc-3.3.0-python3_7/lib/xml2rfc/data
copying xml2rfc/data/SVG-1.2-RFC.rng -> /data-scratch/var-tmp/portage/app-text/xml2rfc-3.3.0/work/xml2rfc-3.3.0-python3_7/lib/xml2rfc/data
copying xml2rfc/data/metadata.js -> /data-scratch/var-tmp/portage/app-text/xml2rfc-3.3.0/work/xml2rfc-3.3.0-python3_7/lib/xml2rfc/data
copying xml2rfc/data/mt.js -> /data-scratch/var-tmp/portage/app-text/xml2rfc-3.3.0/work/xml2rfc-3.3.0-python3_7/lib/xml2rfc/data
copying xml2rfc/data/xml2rfc.css -> /data-scratch/var-tmp/portage/app-text/xml2rfc-3.3.0/work/xml2rfc-3.3.0-python3_7/lib/xml2rfc/data
copying xml2rfc/data/reference.rnc -> /data-scratch/var-tmp/portage/app-text/xml2rfc-3.3.0/work/xml2rfc-3.3.0-python3_7/lib/xml2rfc/data
copying xml2rfc/data/v3compat.dtd -> /data-scratch/var-tmp/portage/app-text/xml2rfc-3.3.0/work/xml2rfc-3.3.0-python3_7/lib/xml2rfc/data
copying xml2rfc/data/rfc7991.rng -> /data-scratch/var-tmp/portage/app-text/xml2rfc-3.3.0/work/xml2rfc-3.3.0-python3_7/lib/xml2rfc/data
copying xml2rfc/data/xmldsig-core-schema.rng.1 -> /data-scratch/var-tmp/portage/app-text/xml2rfc-3.3.0/work/xml2rfc-3.3.0-python3_7/lib/xml2rfc/data
copying xml2rfc/data/v2.rnc -> /data-scratch/var-tmp/portage/app-text/xml2rfc-3.3.0/work/xml2rfc-3.3.0-python3_7/lib/xml2rfc/data
copying xml2rfc/data/rfc7991.rnc -> /data-scratch/var-tmp/portage/app-text/xml2rfc-3.3.0/work/xml2rfc-3.3.0-python3_7/lib/xml2rfc/data
copying xml2rfc/data/br.patch -> /data-scratch/var-tmp/portage/app-text/xml2rfc-3.3.0/work/xml2rfc-3.3.0-python3_7/lib/xml2rfc/data
copying xml2rfc/data/xmldsig-core-schema.rng -> /data-scratch/var-tmp/portage/app-text/xml2rfc-3.3.0/work/xml2rfc-3.3.0-python3_7/lib/xml2rfc/data
copying xml2rfc/data/Scripts.txt -> /data-scratch/var-tmp/portage/app-text/xml2rfc-3.3.0/work/xml2rfc-3.3.0-python3_7/lib/xml2rfc/data
copying xml2rfc/data/xmldsig-core-schema.rnc -> /data-scratch/var-tmp/portage/app-text/xml2rfc-3.3.0/work/xml2rfc-3.3.0-python3_7/lib/xml2rfc/data
copying xml2rfc/data/Strict-Signature.rnc -> /data-scratch/var-tmp/portage/app-text/xml2rfc-3.3.0/work/xml2rfc-3.3.0-python3_7/lib/xml2rfc/data
copying xml2rfc/data/v3compat.rnc -> /data-scratch/var-tmp/portage/app-text/xml2rfc-3.3.0/work/xml2rfc-3.3.0-python3_7/lib/xml2rfc/data
copying xml2rfc/data/xml2rfc-v3-emacs-nxml.rnc -> /data-scratch/var-tmp/portage/app-text/xml2rfc-3.3.0/work/xml2rfc-3.3.0-python3_7/lib/xml2rfc/data
copying xml2rfc/data/v2.rng -> /data-scratch/var-tmp/portage/app-text/xml2rfc-3.3.0/work/xml2rfc-3.3.0-python3_7/lib/xml2rfc/data
copying xml2rfc/data/xmldsig-core-schema.rnc.1 -> /data-scratch/var-tmp/portage/app-text/xml2rfc-3.3.0/work/xml2rfc-3.3.0-python3_7/lib/xml2rfc/data
copying xml2rfc/data/security_any.rnc -> /data-scratch/var-tmp/portage/app-text/xml2rfc-3.3.0/work/xml2rfc-3.3.0-python3_7/lib/xml2rfc/data
copying xml2rfc/data/br2.patch -> /data-scratch/var-tmp/portage/app-text/xml2rfc-3.3.0/work/xml2rfc-3.3.0-python3_7/lib/xml2rfc/data
copying xml2rfc/data/metadata.min.js -> /data-scratch/var-tmp/portage/app-text/xml2rfc-3.3.0/work/xml2rfc-3.3.0-python3_7/lib/xml2rfc/data
copying xml2rfc/data/v3.rng -> /data-scratch/var-tmp/portage/app-text/xml2rfc-3.3.0/work/xml2rfc-3.3.0-python3_7/lib/xml2rfc/data
copying xml2rfc/data/xml2rfc.js -> /data-scratch/var-tmp/portage/app-text/xml2rfc-3.3.0/work/xml2rfc-3.3.0-python3_7/lib/xml2rfc/data
copying xml2rfc/data/security_any.rng -> /data-scratch/var-tmp/portage/app-text/xml2rfc-3.3.0/work/xml2rfc-3.3.0-python3_7/lib/xml2rfc/data
copying xml2rfc/data/reference.rng -> /data-scratch/var-tmp/portage/app-text/xml2rfc-3.3.0/work/xml2rfc-3.3.0-python3_7/lib/xml2rfc/data
copying xml2rfc/data/SVG-1.2-RFC.rnc -> /data-scratch/var-tmp/portage/app-text/xml2rfc-3.3.0/work/xml2rfc-3.3.0-python3_7/lib/xml2rfc/data
warning: build_py: byte-compiling is disabled, skipping.

>>> Source compiled.
>>> Test phase: app-text/xml2rfc-3.3.0
 [32;01m*[0m python3_7: running distutils-r1_run_phase python_test
python3.7 setup.py test --verbose
running test
WARNING: Testing via this command is deprecated and will be removed in a future version. Users looking for a generic test entry point independent of test runner are encouraged to use tox.
running egg_info
writing xml2rfc.egg-info/PKG-INFO
writing dependency_links to xml2rfc.egg-info/dependency_links.txt
writing entry points to xml2rfc.egg-info/entry_points.txt
writing requirements to xml2rfc.egg-info/requires.txt
writing top-level names to xml2rfc.egg-info/top_level.txt
reading manifest file 'xml2rfc.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'xml2rfc.egg-info/SOURCES.txt'
running build_ext
Error: Failure fetching URL https://xml2rfc.ietf.org/public/rfc/bibxml/reference.RFC.2119.xml (HTTPSConnectionPool(host='xml2rfc.ietf.org', port=443): Max retries exceeded with url: /public/rfc/bibxml/reference.RFC.2119.xml (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1911443150>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')))
Error: Failure fetching URL https://xml2rfc.tools.ietf.org/public/rfc/bibxml/reference.RFC.2119.xml (HTTPSConnectionPool(host='xml2rfc.tools.ietf.org', port=443): Max retries exceeded with url: /public/rfc/bibxml/reference.RFC.2119.xml (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1911451a50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')))
Error: Failure fetching URL https://xml2rfc.ietf.org/public/rfc/bibxml/reference.RFC.2119.xml (HTTPSConnectionPool(host='xml2rfc.ietf.org', port=443): Max retries exceeded with url: /public/rfc/bibxml/reference.RFC.2119.xml (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1911458790>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')))
Error: Failure fetching URL https://xml2rfc.tools.ietf.org/public/rfc/bibxml/reference.RFC.2119.xml (HTTPSConnectionPool(host='xml2rfc.tools.ietf.org', port=443): Max retries exceeded with url: /public/rfc/bibxml/reference.RFC.2119.xml (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1911458cd0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')))
Error: Unable to resolve external request: "https://xml2rfc.ietf.org/public/rfc/bibxml/reference.RFC.2119.xml"
Error: Failure fetching URL https://xml2rfc.ietf.org/public/rfc/bibxml/reference.RFC.8174.xml (HTTPSConnectionPool(host='xml2rfc.ietf.org', port=443): Max retries exceeded with url: /public/rfc/bibxml/reference.RFC.8174.xml (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1911458f90>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')))
Error: Failure fetching URL https://xml2rfc.tools.ietf.org/public/rfc/bibxml/reference.RFC.8174.xml (HTTPSConnectionPool(host='xml2rfc.tools.ietf.org', port=443): Max retries exceeded with url: /public/rfc/bibxml/reference.RFC.8174.xml (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1911467950>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')))
Error: Failure fetching URL https://xml2rfc.ietf.org/public/rfc/bibxml/reference.RFC.8174.xml (HTTPSConnectionPool(host='xml2rfc.ietf.org', port=443): Max retries exceeded with url: /public/rfc/bibxml/reference.RFC.8174.xml (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1911467590>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')))
Error: Failure fetching URL https://xml2rfc.tools.ietf.org/public/rfc/bibxml/reference.RFC.8174.xml (HTTPSConnectionPool(host='xml2rfc.tools.ietf.org', port=443): Max retries exceeded with url: /public/rfc/bibxml/reference.RFC.8174.xml (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1911467090>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')))
Error: Unable to resolve external request: "https://xml2rfc.ietf.org/public/rfc/bibxml/reference.RFC.8174.xml"
Error: Failure fetching URL https://xml2rfc.ietf.org/public/rfc/bibxml/reference.RFC.5652.xml (HTTPSConnectionPool(host='xml2rfc.ietf.org', port=443): Max retries exceeded with url: /public/rfc/bibxml/reference.RFC.5652.xml (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1911458090>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')))
Error: Failure fetching URL https://xml2rfc.tools.ietf.org/public/rfc/bibxml/reference.RFC.5652.xml (HTTPSConnectionPool(host='xml2rfc.tools.ietf.org', port=443): Max retries exceeded with url: /public/rfc/bibxml/reference.RFC.5652.xml (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1911467f90>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')))
Error: Failure fetching URL https://xml2rfc.ietf.org/public/rfc/bibxml/reference.RFC.5652.xml (HTTPSConnectionPool(host='xml2rfc.ietf.org', port=443): Max retries exceeded with url: /public/rfc/bibxml/reference.RFC.5652.xml (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f19114584d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')))
Error: Failure fetching URL https://xml2rfc.tools.ietf.org/public/rfc/bibxml/reference.RFC.5652.xml (HTTPSConnectionPool(host='xml2rfc.tools.ietf.org', port=443): Max retries exceeded with url: /public/rfc/bibxml/reference.RFC.5652.xml (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1911451550>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')))
Error: Unable to resolve external request: "https://xml2rfc.ietf.org/public/rfc/bibxml/reference.RFC.5652.xml"
Error: Failure fetching URL https://xml2rfc.ietf.org/public/rfc/bibxml/reference.RFC.5083.xml (HTTPSConnectionPool(host='xml2rfc.ietf.org', port=443): Max retries exceeded with url: /public/rfc/bibxml/reference.RFC.5083.xml (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f19114585d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')))
Error: Failure fetching URL https://xml2rfc.tools.ietf.org/public/rfc/bibxml/reference.RFC.5083.xml (HTTPSConnectionPool(host='xml2rfc.tools.ietf.org', port=443): Max retries exceeded with url: /public/rfc/bibxml/reference.RFC.5083.xml (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f191146e7d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')))
Error: Failure fetching URL https://xml2rfc.ietf.org/public/rfc/bibxml/reference.RFC.5083.xml (HTTPSConnectionPool(host='xml2rfc.ietf.org', port=443): Max retries exceeded with url: /public/rfc/bibxml/reference.RFC.5083.xml (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f191146ecd0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')))
Error: Failure fetching URL https://xml2rfc.tools.ietf.org/public/rfc/bibxml/reference.RFC.5083.xml (HTTPSConnectionPool(host='xml2rfc.tools.ietf.org', port=443): Max retries exceeded with url: /public/rfc/bibxml/reference.RFC.5083.xml (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f191146ec10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')))
Error: Unable to resolve external request: "https://xml2rfc.ietf.org/public/rfc/bibxml/reference.RFC.5083.xml"
Error: Failure fetching URL https://xml2rfc.ietf.org/public/rfc/bibxml3/reference.I-D.levkowetz-xml2rfc-v3-implementation-notes.xml (HTTPSConnectionPool(host='xml2rfc.ietf.org', port=443): Max retries exceeded with url: /public/rfc/bibxml3/reference.I-D.levkowetz-xml2rfc-v3-implementation-notes.xml (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f191146ea10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')))
Error: Failure fetching URL https://xml2rfc.tools.ietf.org/public/rfc/bibxml3/reference.I-D.levkowetz-xml2rfc-v3-implementation-notes.xml (HTTPSConnectionPool(host='xml2rfc.tools.ietf.org', port=443): Max retries exceeded with url: /public/rfc/bibxml3/reference.I-D.levkowetz-xml2rfc-v3-implementation-notes.xml (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f191146e0d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')))
Error: Failure fetching URL https://xml2rfc.ietf.org/public/rfc/bibxml3/reference.I-D.levkowetz-xml2rfc-v3-implementation-notes.xml (HTTPSConnectionPool(host='xml2rfc.ietf.org', port=443): Max retries exceeded with url: /public/rfc/bibxml3/reference.I-D.levkowetz-xml2rfc-v3-implementation-notes.xml (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f191146e710>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')))
Error: Failure fetching URL https://xml2rfc.tools.ietf.org/public/rfc/bibxml3/reference.I-D.levkowetz-xml2rfc-v3-implementation-notes.xml (HTTPSConnectionPool(host='xml2rfc.tools.ietf.org', port=443): Max retries exceeded with url: /public/rfc/bibxml3/reference.I-D.levkowetz-xml2rfc-v3-implementation-notes.xml (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1911451dd0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')))
Error: Unable to resolve external request: "https://xml2rfc.ietf.org/public/rfc/bibxml3/reference.I-D.levkowetz-xml2rfc-v3-implementation-notes.xml"
Error: Failure fetching URL https://xml2rfc.ietf.org/public/rfc/bibxml/reference.RFC.2634.xml (HTTPSConnectionPool(host='xml2rfc.ietf.org', port=443): Max retries exceeded with url: /public/rfc/bibxml/reference.RFC.2634.xml (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1911451ed0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')))
Error: Failure fetching URL https://xml2rfc.tools.ietf.org/public/rfc/bibxml/reference.RFC.2634.xml (HTTPSConnectionPool(host='xml2rfc.tools.ietf.org', port=443): Max retries exceeded with url: /public/rfc/bibxml/reference.RFC.2634.xml (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1911458890>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')))
Error: Failure fetching URL https://xml2rfc.ietf.org/public/rfc/bibxml/reference.RFC.2634.xml (HTTPSConnectionPool(host='xml2rfc.ietf.org', port=443): Max retries exceeded with url: /public/rfc/bibxml/reference.RFC.2634.xml (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1911458d90>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')))
Error: Failure fetching URL https://xml2rfc.tools.ietf.org/public/rfc/bibxml/reference.RFC.2634.xml (HTTPSConnectionPool(host='xml2rfc.tools.ietf.org', port=443): Max retries exceeded with url: /public/rfc/bibxml/reference.RFC.2634.xml (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1911458150>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')))
Error: Unable to resolve external request: "https://xml2rfc.ietf.org/public/rfc/bibxml/reference.RFC.2634.xml"
Error: Failure fetching URL https://xml2rfc.ietf.org/public/rfc/bibxml/reference.RFC.5035.xml (HTTPSConnectionPool(host='xml2rfc.ietf.org', port=443): Max retries exceeded with url: /public/rfc/bibxml/reference.RFC.5035.xml (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1911467f50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')))
Error: Failure fetching URL https://xml2rfc.tools.ietf.org/public/rfc/bibxml/reference.RFC.5035.xml (HTTPSConnectionPool(host='xml2rfc.tools.ietf.org', port=443): Max retries exceeded with url: /public/rfc/bibxml/reference.RFC.5035.xml (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1911467750>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')))
Error: Failure fetching URL https://xml2rfc.ietf.org/public/rfc/bibxml/reference.RFC.5035.xml (HTTPSConnectionPool(host='xml2rfc.ietf.org', port=443): Max retries exceeded with url: /public/rfc/bibxml/reference.RFC.5035.xml (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1911458f90>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')))
Error: Failure fetching URL https://xml2rfc.tools.ietf.org/public/rfc/bibxml/reference.RFC.5035.xml (HTTPSConnectionPool(host='xml2rfc.tools.ietf.org', port=443): Max retries exceeded with url: /public/rfc/bibxml/reference.RFC.5035.xml (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1911458350>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')))
Error: Unable to resolve external request: "https://xml2rfc.ietf.org/public/rfc/bibxml/reference.RFC.5035.xml"
Error: Failure fetching URL https://xml2rfc.ietf.org/public/rfc/bibxml/reference.RFC.2045.xml (HTTPSConnectionPool(host='xml2rfc.ietf.org', port=443): Max retries exceeded with url: /public/rfc/bibxml/reference.RFC.2045.xml (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1911458a10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')))
Error: Failure fetching URL https://xml2rfc.tools.ietf.org/public/rfc/bibxml/reference.RFC.2045.xml (HTTPSConnectionPool(host='xml2rfc.tools.ietf.org', port=443): Max retries exceeded with url: /public/rfc/bibxml/reference.RFC.2045.xml (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1911458d10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')))
Error: Failure fetching URL https://xml2rfc.ietf.org/public/rfc/bibxml/reference.RFC.2045.xml (HTTPSConnectionPool(host='xml2rfc.ietf.org', port=443): Max retries exceeded with url: /public/rfc/bibxml/reference.RFC.2045.xml (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1911451f10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')))
Error: Failure fetching URL https://xml2rfc.tools.ietf.org/public/rfc/bibxml/reference.RFC.2045.xml (HTTPSConnectionPool(host='xml2rfc.tools.ietf.org', port=443): Max retries exceeded with url: /public/rfc/bibxml/reference.RFC.2045.xml (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1911467f50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')))
Error: Unable to resolve external request: "https://xml2rfc.ietf.org/public/rfc/bibxml/reference.RFC.2045.xml"
Error: Failure fetching URL https://xml2rfc.ietf.org/public/rfc/bibxml/reference.RFC.2046.xml (HTTPSConnectionPool(host='xml2rfc.ietf.org', port=443): Max retries exceeded with url: /public/rfc/bibxml/reference.RFC.2046.xml (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1911467290>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')))
Error: Failure fetching URL https://xml2rfc.tools.ietf.org/public/rfc/bibxml/reference.RFC.2046.xml (HTTPSConnectionPool(host='xml2rfc.tools.ietf.org', port=443): Max retries exceeded with url: /public/rfc/bibxml/reference.RFC.2046.xml (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f19114678d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')))
Error: Failure fetching URL https://xml2rfc.ietf.org/public/rfc/bibxml/reference.RFC.2046.xml (HTTPSConnectionPool(host='xml2rfc.ietf.org', port=443): Max retries exceeded with url: /public/rfc/bibxml/reference.RFC.2046.xml (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f191146e090>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')))
Error: Failure fetching URL https://xml2rfc.tools.ietf.org/public/rfc/bibxml/reference.RFC.2046.xml (HTTPSConnectionPool(host='xml2rfc.tools.ietf.org', port=443): Max retries exceeded with url: /public/rfc/bibxml/reference.RFC.2046.xml (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1911467150>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')))
Error: Unable to resolve external request: "https://xml2rfc.ietf.org/public/rfc/bibxml/reference.RFC.2046.xml"
Error: Failure fetching URL https://xml2rfc.ietf.org/public/rfc/bibxml/reference.RFC.2047.xml (HTTPSConnectionPool(host='xml2rfc.ietf.org', port=443): Max retries exceeded with url: /public/rfc/bibxml/reference.RFC.2047.xml (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1911467b50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')))
Error: Failure fetching URL https://xml2rfc.tools.ietf.org/public/rfc/bibxml/reference.RFC.2047.xml (HTTPSConnectionPool(host='xml2rfc.tools.ietf.org', port=443): Max retries exceeded with url: /public/rfc/bibxml/reference.RFC.2047.xml (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f191146e110>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')))
Error: Failure fetching URL https://xml2rfc.ietf.org/public/rfc/bibxml/reference.RFC.2047.xml (HTTPSConnectionPool(host='xml2rfc.ietf.org', port=443): Max retries exceeded with url: /public/rfc/bibxml/reference.RFC.2047.xml (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f191146ea10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')))
Error: Failure fetching URL https://xml2rfc.tools.ietf.org/public/rfc/bibxml/reference.RFC.2047.xml (HTTPSConnectionPool(host='xml2rfc.tools.ietf.org', port=443): Max retries exceeded with url: /public/rfc/bibxml/reference.RFC.2047.xml (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1911467c90>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')))
Error: Unable to resolve external request: "https://xml2rfc.ietf.org/public/rfc/bibxml/reference.RFC.2047.xml"
Error: Failure fetching URL https://xml2rfc.ietf.org/public/rfc/bibxml/reference.RFC.2049.xml (HTTPSConnectionPool(host='xml2rfc.ietf.org', port=443): Max retries exceeded with url: /public/rfc/bibxml/reference.RFC.2049.xml (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1911467690>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')))
Error: Failure fetching URL https://xml2rfc.tools.ietf.org/public/rfc/bibxml/reference.RFC.2049.xml (HTTPSConnectionPool(host='xml2rfc.tools.ietf.org', port=443): Max retries exceeded with url: /public/rfc/bibxml/reference.RFC.2049.xml (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f191146ec90>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')))
Error: Failure fetching URL https://xml2rfc.ietf.org/public/rfc/bibxml/reference.RFC.2049.xml (HTTPSConnectionPool(host='xml2rfc.ietf.org', port=443): Max retries exceeded with url: /public/rfc/bibxml/reference.RFC.2049.xml (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1911443150>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')))
Error: Failure fetching URL https://xml2rfc.tools.ietf.org/public/rfc/bibxml/reference.RFC.2049.xml (HTTPSConnectionPool(host='xml2rfc.tools.ietf.org', port=443): Max retries exceeded with url: /public/rfc/bibxml/reference.RFC.2049.xml (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1911451250>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')))
Error: Unable to resolve external request: "https://xml2rfc.ietf.org/public/rfc/bibxml/reference.RFC.2049.xml"
Error: Failure fetching URL https://xml2rfc.ietf.org/public/rfc/bibxml/reference.RFC.6838.xml (HTTPSConnectionPool(host='xml2rfc.ietf.org', port=443): Max retries exceeded with url: /public/rfc/bibxml/reference.RFC.6838.xml (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1911451850>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')))
Error: Failure fetching URL https://xml2rfc.tools.ietf.org/public/rfc/bibxml/reference.RFC.6838.xml (HTTPSConnectionPool(host='xml2rfc.tools.ietf.org', port=443): Max retries exceeded with url: /public/rfc/bibxml/reference.RFC.6838.xml (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1911458890>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')))
Error: Failure fetching URL https://xml2rfc.ietf.org/public/rfc/bibxml/reference.RFC.6838.xml (HTTPSConnectionPool(host='xml2rfc.ietf.org', port=443): Max retries exceeded with url: /public/rfc/bibxml/reference.RFC.6838.xml (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1911458e50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')))
Error: Failure fetching URL https://xml2rfc.tools.ietf.org/public/rfc/bibxml/reference.RFC.6838.xml (HTTPSConnectionPool(host='xml2rfc.tools.ietf.org', port=443): Max retries exceeded with url: /public/rfc/bibxml/reference.RFC.6838.xml (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1911478910>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')))
Error: Unable to resolve external request: "https://xml2rfc.ietf.org/public/rfc/bibxml/reference.RFC.6838.xml"
Error: Failure fetching URL https://xml2rfc.ietf.org/public/rfc/bibxml/reference.RFC.4289.xml (HTTPSConnectionPool(host='xml2rfc.ietf.org', port=443): Max retries exceeded with url: /public/rfc/bibxml/reference.RFC.4289.xml (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f19114b6d50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')))
Error: Failure fetching URL https://xml2rfc.tools.ietf.org/public/rfc/bibxml/reference.RFC.4289.xml (HTTPSConnectionPool(host='xml2rfc.tools.ietf.org', port=443): Max retries exceeded with url: /public/rfc/bibxml/reference.RFC.4289.xml (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1911451610>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')))
Error: Failure fetching URL https://xml2rfc.ietf.org/public/rfc/bibxml/reference.RFC.4289.xml (HTTPSConnectionPool(host='xml2rfc.ietf.org', port=443): Max retries exceeded with url: /public/rfc/bibxml/reference.RFC.4289.xml (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1911451cd0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')))
Error: Failure fetching URL https://xml2rfc.tools.ietf.org/public/rfc/bibxml/reference.RFC.4289.xml (HTTPSConnectionPool(host='xml2rfc.tools.ietf.org', port=443): Max retries exceeded with url: /public/rfc/bibxml/reference.RFC.4289.xml (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1911467610>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')))
Error: Unable to resolve external request: "https://xml2rfc.ietf.org/public/rfc/bibxml/reference.RFC.4289.xml"
Error: Failure fetching URL https://xml2rfc.ietf.org/public/rfc/bibxml/reference.RFC.0952.xml (HTTPSConnectionPool(host='xml2rfc.ietf.org', port=443): Max retries exceeded with url: /public/rfc/bibxml/reference.RFC.0952.xml (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1911467210>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')))
Error: Failure fetching URL https://xml2rfc.tools.ietf.org/public/rfc/bibxml/reference.RFC.0952.xml (HTTPSConnectionPool(host='xml2rfc.tools.ietf.org', port=443): Max retries exceeded with url: /public/rfc/bibxml/reference.RFC.0952.xml (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f19114582d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')))
Error: Failure fetching URL https://xml2rfc.ietf.org/public/rfc/bibxml/reference.RFC.0952.xml (HTTPSConnectionPool(host='xml2rfc.ietf.org', port=443): Max retries exceeded with url: /public/rfc/bibxml/reference.RFC.0952.xml (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1911467310>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')))
Error: Failure fetching URL https://xml2rfc.tools.ietf.org/public/rfc/bibxml/reference.RFC.0952.xml (HTTPSConnectionPool(host='xml2rfc.tools.ietf.org', port=443): Max retries exceeded with url: /public/rfc/bibxml/reference.RFC.0952.xml (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1911458590>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')))
Error: Unable to resolve external request: "https://xml2rfc.ietf.org/public/rfc/bibxml/reference.RFC.0952.xml"
test (unittest.loader._FailedTest) ... ERROR

======================================================================
ERROR: test (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test
Traceback (most recent call last):
  File "/data-scratch/var-tmp/portage/app-text/xml2rfc-3.3.0/work/xml2rfc-3.3.0/xml2rfc/writers/base.py", line 1840, in xinclude
    self.tree.xinclude()
  File "src/lxml/etree.pyx", line 2366, in lxml.etree._ElementTree.xinclude
  File "src/lxml/xinclude.pxi", line 64, in lxml.etree.XInclude.__call__
lxml.etree.XIncludeError: could not load https://xml2rfc.ietf.org/public/rfc/bibxml/reference.RFC.2119.xml, and no fallback was found, line 1187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/data-scratch/var-tmp/portage/app-text/xml2rfc-3.3.0/work/xml2rfc-3.3.0/test.py", line 465, in <module>
    elements_pdfdoc = elements_writer.pdf() # has side effects on .root
  File "/data-scratch/var-tmp/portage/app-text/xml2rfc-3.3.0/work/xml2rfc-3.3.0/xml2rfc/writers/pdf.py", line 62, in pdf
    tree = prep.prep()
  File "/data-scratch/var-tmp/portage/app-text/xml2rfc-3.3.0/work/xml2rfc-3.3.0/xml2rfc/writers/preptool.py", line 203, in prep
    self.xinclude()
  File "/data-scratch/var-tmp/portage/app-text/xml2rfc-3.3.0/work/xml2rfc-3.3.0/xml2rfc/writers/base.py", line 1842, in xinclude
    self.die(None, "XInclude processing failed: %s" % e)
  File "/data-scratch/var-tmp/portage/app-text/xml2rfc-3.3.0/work/xml2rfc-3.3.0/xml2rfc/writers/base.py", line 1827, in die
    raise RfcWriterError(msg)
xml2rfc.writers.base.RfcWriterError: Error: XInclude processing failed: could not load https://xml2rfc.ietf.org/public/rfc/bibxml/reference.RFC.2119.xml, and no fallback was found, line 1187


----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
Test failed: <unittest.runner.TextTestResult run=1 errors=1 failures=0>
Error: XInclude processing failed: could not load https://xml2rfc.ietf.org/public/rfc/bibxml/reference.RFC.2119.xml, and no fallback was found, line 1187
error: Test failed: <unittest.runner.TextTestResult run=1 errors=1 failures=0>
 [31;01m*[0m ERROR: app-text/xml2rfc-3.3.0::flow failed (test phase):
 [31;01m*[0m   Tests fail with python3.7
 [31;01m*[0m 
 [31;01m*[0m Call stack:
 [31;01m*[0m     ebuild.sh, line  125:  Called src_test
 [31;01m*[0m   environment, line 2946:  Called distutils-r1_src_test
 [31;01m*[0m   environment, line 1256:  Called _distutils-r1_run_foreach_impl 'python_test'
 [31;01m*[0m   environment, line  472:  Called python_foreach_impl 'distutils-r1_run_phase' 'python_test'
 [31;01m*[0m   environment, line 2555:  Called multibuild_foreach_variant '_python_multibuild_wrapper' 'distutils-r1_run_phase' 'python_test'
 [31;01m*[0m   environment, line 2038:  Called _multibuild_run '_python_multibuild_wrapper' 'distutils-r1_run_phase' 'python_test'
 [31;01m*[0m   environment, line 2036:  Called _python_multibuild_wrapper 'distutils-r1_run_phase' 'python_test'
 [31;01m*[0m   environment, line  829:  Called distutils-r1_run_phase 'python_test'
 [31;01m*[0m   environment, line 1193:  Called python_test
 [31;01m*[0m   environment, line 2906:  Called die
 [31;01m*[0m The specific snippet of code:
 [31;01m*[0m       nonfatal esetup.py test --verbose || die "Tests fail with ${EPYTHON}"
 [31;01m*[0m 
 [31;01m*[0m If you need support, post the output of `emerge --info '=app-text/xml2rfc-3.3.0::flow'`,
 [31;01m*[0m the complete build log and the output of `emerge -pqv '=app-text/xml2rfc-3.3.0::flow'`.
 [31;01m*[0m The complete build log is located at '/data-scratch/var-tmp/portage/app-text/xml2rfc-3.3.0/temp/build.log'.
 [31;01m*[0m The ebuild environment file is located at '/data-scratch/var-tmp/portage/app-text/xml2rfc-3.3.0/temp/environment'.
 [31;01m*[0m Working directory: '/data-scratch/var-tmp/portage/app-text/xml2rfc-3.3.0/work/xml2rfc-3.3.0'
 [31;01m*[0m S: '/data-scratch/var-tmp/portage/app-text/xml2rfc-3.3.0/work/xml2rfc-3.3.0'
